---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: verify | gitlab_ce:gitlab_ee
  hosts: gitlab_ce:gitlab_ee
  remote_user: root
  become: true
  tasks:
    - name: gitlab --version
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      ansible.builtin.command:
        cmd: gitlab --version
      register: result
      changed_when: result is not succeeded

- name: verify | gitlab_runner
  hosts: gitlab_runner
  remote_user: root
  become: true
  tasks:
    - name: /usr/bin/packer --version
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      ansible.builtin.command:
        cmd: /usr/bin/packer --version
      register: result
      changed_when: result is not succeeded

    - name: docker version
      ansible.builtin.command:
        cmd: docker version
      register: result
      changed_when: result is not succeeded

    - name: VBoxManage --version
      ansible.builtin.command:
        cmd: VBoxManage --version
      register: result
      changed_when: result is not succeeded

    - name: virsh --version
      ansible.builtin.command:
        cmd: virsh --version
      register: result
      changed_when: result is not succeeded

    - name: gitlab-runner --version
      ansible.builtin.command:
        cmd: gitlab-runner --version
      register: result
      changed_when: result is not succeeded
